### ISSUE TITLE
Crash when cluster name not specified on apply

### ISSUE THREAD

**Issue by aslafy-z** [pharmer/pharmer#360]
When running `pharmer apply` without any cluster name, it crashs instead of erroring cleanly.  
Running `0.1.0-alpha.1` on Ubuntu 16.04, with go `1.9.2`. 

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pharmer/pharmer/cloud/cmds.NewCmdApply.func1(0xc4202afb00, 0xc420185eb0, 0x0, 0x1)
        /home/zadkiel/.go/src/github.com/pharmer/pharmer/cloud/cmds/apply.go:21 +0x418
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202afb00, 0xc420185e70, 0x1, 0x1, 0xc4202afb00, 0xc420185e70)
        /home/zadkiel/.go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420272480, 0xc420272d80, 0xc420764a00, 0xc4201857b8)
        /home/zadkiel/.go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420272480, 0xc420074000, 0x39be220)
        /home/zadkiel/.go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /home/zadkiel/.go/src/github.com/pharmer/pharmer/main.go:18 +0xb1
```

**Comment by tamalsaha** [comment]
Hey,
I cut a new release for 0.1.0-rc.0. https://github.com/pharmer/pharmer/releases/tag/0.1.0-rc.0

Can you please try with that? Please reopen if you still see this issue.
