### ISSUE TITLE
panic: unknown provider

### ISSUE THREAD

**Issue by jwilm** [pharmer/pharmer#484]
Hi there,

I am following the user guide for Packet and got as far as installing and running

```
pharmer create credential pack
```

Here's the output:

```
? Choose a Cloud provider: packet
panic: unknown provider

goroutine 1 [running]:
github.com/pharmer/pharmer/vendor/github.com/pharmer/cloud/pkg/credential.GetFormat(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jwilm/go/src/github.com/pharmer/pharmer/vendor/github.com/pharmer/cloud/pkg/credential/types.go:172 +0x1830
github.com/pharmer/pharmer/credential/cmds.RunCreateCredential(0x31d9fa0, 0xc00067a0c0, 0xc0000e0780, 0x2c7ccb0, 0x4)
	/home/jwilm/go/src/github.com/pharmer/pharmer/credential/cmds/create.go:116 +0x304
github.com/pharmer/pharmer/credential/cmds.NewCmdCreateCredential.func1(0xc0006a9180, 0xc0006fea00, 0x1, 0x1)
	/home/jwilm/go/src/github.com/pharmer/pharmer/credential/cmds/create.go:48 +0x1bd
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006a9180, 0xc0006fe9c0, 0x1, 0x1, 0xc0006a9180, 0xc0006fe9c0)
	/home/jwilm/go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006a8500, 0xc000010010, 0x3172640, 0xc000010018)
	/home/jwilm/go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/pharmer/pharmer/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/jwilm/go/src/github.com/pharmer/pharmer/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/home/jwilm/go/src/github.com/pharmer/pharmer/main.go:18 +0xb2
```

No matter which cloud provider I select, it always panics with `unknown provider`.

**Comment by tahsinrahman** [comment]
Thanks for reporting this, we're looking into this. in the meantime, you can try running with `--provider` flag
```
pharmer create credential pack --provider packet
```

**Comment by tahsinrahman** [comment]
@jwilm you can use release 0.3.1 now that fixes this issue https://github.com/pharmer/pharmer/releases/tag/0.3.1

**Comment by jwilm** [comment]
Thanks! The patch works for me. Unbelievable response time closing out this issue :smile:
